package com.codeops.fleet.dto.mapper;

import com.codeops.fleet.dto.request.CreateServiceProfileRequest;
import com.codeops.fleet.dto.response.NetworkConfigResponse;
import com.codeops.fleet.dto.response.ServiceProfileDetailResponse;
import com.codeops.fleet.dto.response.ServiceProfileResponse;
import com.codeops.fleet.dto.response.VolumeMountResponse;
import com.codeops.fleet.entity.ServiceProfile;
import org.mapstruct.Builder;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

/**
 * MapStruct mapper for ServiceProfile entity to/from DTOs.
 */
@Mapper(componentModel = "spring", builder = @Builder(disableBuilder = true))
public interface ServiceProfileMapper {

    /**
     * Maps a service profile to a lightweight list-view response.
     *
     * @param entity the service profile entity
     * @return the list-view response DTO
     */
    @Mapping(target = "isAutoGenerated", source = "autoGenerated")
    @Mapping(target = "isEnabled", source = "enabled")
    @Mapping(target = "serviceRegistrationId",
            expression = "java(entity.getServiceRegistration() != null ? entity.getServiceRegistration().getId() : null)")
    ServiceProfileResponse toResponse(ServiceProfile entity);

    /**
     * Maps a service profile to a full detail response with volumes and networks.
     *
     * @param entity   the service profile entity
     * @param volumes  the volume mount responses
     * @param networks the network config responses
     * @return the detail response DTO
     */
    @Mapping(target = "isAutoGenerated", source = "entity.autoGenerated")
    @Mapping(target = "isEnabled", source = "entity.enabled")
    @Mapping(target = "serviceRegistrationId",
            expression = "java(entity.getServiceRegistration() != null ? entity.getServiceRegistration().getId() : null)")
    @Mapping(source = "entity.team.id", target = "teamId")
    @Mapping(source = "volumes", target = "volumes")
    @Mapping(source = "networks", target = "networks")
    @Mapping(target = "envVarsJson", ignore = true)
    @Mapping(target = "portsJson", ignore = true)
    ServiceProfileDetailResponse toDetailResponse(ServiceProfile entity,
                                                   List<VolumeMountResponse> volumes,
                                                   List<NetworkConfigResponse> networks);

    /**
     * Maps a list of service profiles to list-view responses.
     *
     * @param entities the service profile entities
     * @return the list of response DTOs
     */
    List<ServiceProfileResponse> toResponseList(List<ServiceProfile> entities);

    /**
     * Maps a create request to a new ServiceProfile entity.
     *
     * @param request the create service profile request
     * @return the ServiceProfile entity
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "entrypoint", ignore = true)
    @Mapping(target = "team", ignore = true)
    @Mapping(target = "serviceRegistration", ignore = true)
    @Mapping(target = "autoGenerated", constant = "false")
    @Mapping(target = "enabled", constant = "true")
    @Mapping(target = "volumeMounts", ignore = true)
    @Mapping(target = "networkConfigs", ignore = true)
    @Mapping(target = "portMappings", ignore = true)
    @Mapping(target = "environmentVariables", ignore = true)
    ServiceProfile toEntity(CreateServiceProfileRequest request);
}
