package com.codeops.fleet.entity;

import com.codeops.entity.BaseEntity;
import com.codeops.entity.Team;
import com.codeops.fleet.entity.enums.RestartPolicy;
import com.codeops.registry.entity.ServiceRegistration;
import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

/**
 * Docker-specific execution configuration for a service.
 *
 * <p>A service profile defines how a Docker container should be created and run,
 * including image, command, health checks, resource limits, and child configurations
 * (ports, volumes, networks, environment variables). Profiles may be auto-generated
 * from Registry's {@link ServiceRegistration} or manually created.</p>
 */
@Entity
@Table(name = "fleet_service_profiles",
        uniqueConstraints = @UniqueConstraint(
                name = "uk_fsp_team_service_name",
                columnNames = {"team_id", "service_name"}),
        indexes = {
                @Index(name = "idx_fsp_team_id", columnList = "team_id"),
                @Index(name = "idx_fsp_service_name", columnList = "service_name")
        })
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ServiceProfile extends BaseEntity {

    /** Service name matching Registry if linked, or a custom name. */
    @Column(name = "service_name", nullable = false, length = 200)
    private String serviceName;

    /** Human-friendly display name for this profile. */
    @Column(name = "display_name", length = 200)
    private String displayName;

    /** Detailed description of this service profile's purpose. */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /** Docker image name (e.g., {@code postgres}, {@code nginx}). */
    @Column(name = "image_name", nullable = false, length = 500)
    private String imageName;

    /** Docker image tag (e.g., {@code 16}, {@code latest}). */
    @Builder.Default
    @Column(name = "image_tag", length = 100)
    private String imageTag = "latest";

    /** Override for the container CMD instruction. */
    @Column(name = "command", columnDefinition = "TEXT")
    private String command;

    /** Override for the container ENTRYPOINT instruction. */
    @Column(name = "entrypoint", columnDefinition = "TEXT")
    private String entrypoint;

    /** Working directory inside the container. */
    @Column(name = "working_dir", length = 500)
    private String workingDir;

    /** Shell command used for container health checks. */
    @Column(name = "health_check_command", columnDefinition = "TEXT")
    private String healthCheckCommand;

    /** Interval in seconds between health check executions. */
    @Builder.Default
    @Column(name = "health_check_interval_seconds")
    private Integer healthCheckIntervalSeconds = 30;

    /** Timeout in seconds for each health check execution. */
    @Builder.Default
    @Column(name = "health_check_timeout_seconds")
    private Integer healthCheckTimeoutSeconds = 10;

    /** Number of consecutive failures before marking container unhealthy. */
    @Builder.Default
    @Column(name = "health_check_retries")
    private Integer healthCheckRetries = 3;

    /** Docker restart policy applied to containers created from this profile. */
    @Builder.Default
    @Enumerated(EnumType.STRING)
    @Column(name = "restart_policy", nullable = false)
    private RestartPolicy restartPolicy = RestartPolicy.UNLESS_STOPPED;

    /** Memory limit in megabytes for the container. */
    @Column(name = "memory_limit_mb")
    private Integer memoryLimitMb;

    /** CPU limit for the container (e.g., 1.5 means 1.5 CPU cores). */
    @Column(name = "cpu_limit")
    private Double cpuLimit;

    /** Start priority order — lower values start first during orchestration. */
    @Builder.Default
    @Column(name = "start_order", nullable = false)
    private Integer startOrder = 0;

    /** Whether this profile was auto-generated from a Registry sync. */
    @Builder.Default
    @Column(name = "is_auto_generated", nullable = false)
    private boolean isAutoGenerated = false;

    /** Whether this profile is enabled and available for use. */
    @Builder.Default
    @Column(name = "is_enabled", nullable = false)
    private boolean isEnabled = true;

    /** Linked Registry service registration, if this profile was generated from Registry. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "service_registration_id")
    private ServiceRegistration serviceRegistration;

    /** Team that owns this service profile. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "team_id", nullable = false)
    private Team team;

    /** Volume mounts configured for this service profile. */
    @Builder.Default
    @OneToMany(mappedBy = "serviceProfile", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<VolumeMount> volumeMounts = new ArrayList<>();

    /** Network configurations for this service profile. */
    @Builder.Default
    @OneToMany(mappedBy = "serviceProfile", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<NetworkConfig> networkConfigs = new ArrayList<>();

    /** Port mappings configured for this service profile. */
    @Builder.Default
    @OneToMany(mappedBy = "serviceProfile", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<PortMapping> portMappings = new ArrayList<>();

    /** Environment variables configured for this service profile. */
    @Builder.Default
    @OneToMany(mappedBy = "serviceProfile", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<EnvironmentVariable> environmentVariables = new ArrayList<>();
}
