package com.codeops.fleet.dto.response;

import com.codeops.fleet.entity.enums.RestartPolicy;

import java.time.Instant;
import java.util.UUID;

/** Lightweight service profile response for list views. */
public record ServiceProfileResponse(
        UUID id,
        String serviceName,
        String displayName,
        String imageName,
        String imageTag,
        RestartPolicy restartPolicy,
        Boolean isAutoGenerated,
        Boolean isEnabled,
        Integer startOrder,
        UUID serviceRegistrationId,
        Instant createdAt
) {}
