package com.codeops.fleet.dto.response;

import com.codeops.fleet.entity.enums.RestartPolicy;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/** Full service profile detail response including volumes and networks. */
public record ServiceProfileDetailResponse(
        UUID id,
        String serviceName,
        String displayName,
        String description,
        String imageName,
        String imageTag,
        String command,
        String workingDir,
        String envVarsJson,
        String portsJson,
        String healthCheckCommand,
        Integer healthCheckIntervalSeconds,
        Integer healthCheckTimeoutSeconds,
        Integer healthCheckRetries,
        RestartPolicy restartPolicy,
        Integer memoryLimitMb,
        Double cpuLimit,
        Boolean isAutoGenerated,
        Boolean isEnabled,
        Integer startOrder,
        UUID serviceRegistrationId,
        UUID teamId,
        List<VolumeMountResponse> volumes,
        List<NetworkConfigResponse> networks,
        Instant createdAt,
        Instant updatedAt
) {}
