package com.codeops.fleet.config;

import com.codeops.entity.Team;
import com.codeops.entity.User;
import com.codeops.fleet.entity.*;
import com.codeops.fleet.entity.enums.RestartPolicy;
import com.codeops.fleet.repository.*;
import com.codeops.registry.entity.ServiceRegistration;
import com.codeops.registry.entity.enums.ServiceType;
import com.codeops.registry.repository.ServiceRegistrationRepository;
import com.codeops.repository.TeamRepository;
import com.codeops.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Profile;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.List;

/**
 * Seeds development data for the Fleet module.
 *
 * <p>Auto-generates service profiles from existing Registry service registrations,
 * creates a default solution profile grouping all generated services, and creates
 * a default workstation profile for the seed user.</p>
 *
 * <p>Only active under the {@code dev} profile. Skips seeding if fleet data
 * already exists.</p>
 */
@Profile("dev")
@Component
@Order(200)
@RequiredArgsConstructor
@Slf4j
public class FleetDataSeeder implements CommandLineRunner {

    private final ServiceProfileRepository serviceProfileRepository;
    private final SolutionProfileRepository solutionProfileRepository;
    private final SolutionServiceRepository solutionServiceRepository;
    private final WorkstationProfileRepository workstationProfileRepository;
    private final WorkstationSolutionRepository workstationSolutionRepository;
    private final PortMappingRepository portMappingRepository;
    private final ServiceRegistrationRepository serviceRegistrationRepository;
    private final UserRepository userRepository;
    private final TeamRepository teamRepository;

    private User adam;
    private Team team;

    @Override
    @Transactional
    public void run(String... args) {
        loadReferences();
        if (team == null || adam == null) {
            log.warn("Fleet seeder skipped — core data not yet available");
            return;
        }

        if (!serviceProfileRepository.findByTeamId(team.getId()).isEmpty()) {
            log.info("Fleet data already seeded — skipping");
            return;
        }

        List<ServiceProfile> profiles = seedServiceProfiles();
        SolutionProfile solution = seedDefaultSolution(profiles);
        seedDefaultWorkstation(solution);
        log.info("Fleet development data seeded successfully");
    }

    /**
     * Loads the seed user and team references from the core DataSeeder.
     */
    private void loadReferences() {
        adam = userRepository.findByEmail("adam@allard.com").orElse(null);
        team = teamRepository.findAll().stream().findFirst().orElse(null);
    }

    /**
     * Creates service profiles from all Registry service registrations for the team.
     *
     * @return the list of created service profiles
     */
    private List<ServiceProfile> seedServiceProfiles() {
        List<ServiceRegistration> registrations = serviceRegistrationRepository.findByTeamId(team.getId());
        List<ServiceProfile> profiles = new ArrayList<>();

        for (int i = 0; i < registrations.size(); i++) {
            ServiceRegistration reg = registrations.get(i);
            ImageMapping mapping = getImageMapping(reg.getServiceType());

            ServiceProfile profile = ServiceProfile.builder()
                    .serviceName(reg.getName())
                    .displayName(reg.getName())
                    .description("Auto-generated from Registry: " + reg.getName())
                    .imageName(mapping.imageName())
                    .imageTag(mapping.imageTag())
                    .restartPolicy(RestartPolicy.UNLESS_STOPPED)
                    .isAutoGenerated(true)
                    .isEnabled(true)
                    .startOrder(i)
                    .serviceRegistration(reg)
                    .team(team)
                    .build();
            profile = serviceProfileRepository.save(profile);

            if (mapping.defaultPort() != null) {
                PortMapping portMapping = PortMapping.builder()
                        .hostPort(mapping.defaultPort())
                        .containerPort(mapping.defaultPort())
                        .protocol("tcp")
                        .serviceProfile(profile)
                        .build();
                portMappingRepository.save(portMapping);
            }

            profiles.add(profile);
        }

        log.info("Seeded {} service profiles from Registry", profiles.size());
        return profiles;
    }

    /**
     * Creates the default solution profile containing all generated service profiles.
     *
     * @param profiles the service profiles to include
     * @return the created solution profile
     */
    private SolutionProfile seedDefaultSolution(List<ServiceProfile> profiles) {
        SolutionProfile solution = SolutionProfile.builder()
                .name("Default Solution")
                .description("Auto-generated solution containing all registered services")
                .isDefault(true)
                .team(team)
                .build();
        solution = solutionProfileRepository.save(solution);

        for (int i = 0; i < profiles.size(); i++) {
            SolutionService link = SolutionService.builder()
                    .solutionProfile(solution)
                    .serviceProfile(profiles.get(i))
                    .startOrder(i)
                    .build();
            solutionServiceRepository.save(link);
        }

        log.info("Seeded default solution profile with {} services", profiles.size());
        return solution;
    }

    /**
     * Creates the default workstation profile for the seed user, linked to the default solution.
     *
     * @param solution the solution profile to include
     */
    private void seedDefaultWorkstation(SolutionProfile solution) {
        WorkstationProfile workstation = WorkstationProfile.builder()
                .name("Default Workstation")
                .description("Auto-generated workstation for local development")
                .isDefault(true)
                .user(adam)
                .team(team)
                .build();
        workstation = workstationProfileRepository.save(workstation);

        WorkstationSolution link = WorkstationSolution.builder()
                .workstationProfile(workstation)
                .solutionProfile(solution)
                .startOrder(0)
                .build();
        workstationSolutionRepository.save(link);

        log.info("Seeded default workstation profile for user '{}'", adam.getEmail());
    }

    /**
     * Maps a Registry service type to the default Docker image and port.
     *
     * @param serviceType the Registry service type
     * @return the image mapping
     */
    private ImageMapping getImageMapping(ServiceType serviceType) {
        return switch (serviceType) {
            case SPRING_BOOT_API -> new ImageMapping("eclipse-temurin", "21-jre", 8080);
            case FLUTTER_WEB -> new ImageMapping("nginx", "alpine", 80);
            case REACT_SPA -> new ImageMapping("nginx", "alpine", 3000);
            case EXPRESS_API -> new ImageMapping("node", "20-alpine", 3000);
            case FASTAPI -> new ImageMapping("python", "3.12-slim", 8000);
            case DOTNET_API -> new ImageMapping("mcr.microsoft.com/dotnet/aspnet", "8.0", 5000);
            case GO_API -> new ImageMapping("golang", "1.22-alpine", 8080);
            case DATABASE_SERVICE -> new ImageMapping("postgres", "16", 5432);
            case MESSAGE_BROKER -> new ImageMapping("confluentinc/cp-kafka", "7.5.0", 9092);
            case CACHE_SERVICE -> new ImageMapping("redis", "7-alpine", 6379);
            default -> new ImageMapping("alpine", "latest", null);
        };
    }

    /**
     * Holds the default Docker image mapping for a service type.
     *
     * @param imageName   the Docker image name
     * @param imageTag    the Docker image tag
     * @param defaultPort the default port, or null if none
     */
    private record ImageMapping(String imageName, String imageTag, Integer defaultPort) {}
}
