package com.codeops.fleet.entity;

import com.codeops.entity.Team;
import com.codeops.entity.User;
import com.codeops.fleet.entity.enums.RestartPolicy;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.test.context.ActiveProfiles;

import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Entity tests for {@link ServiceProfile}.
 *
 * <p>Verifies persistence, default field values, boolean field defaults,
 * collection initializations, and cascade behavior for child entities.</p>
 */
@DataJpaTest
@ActiveProfiles("test")
class ServiceProfileTest {

    @Autowired
    private TestEntityManager em;

    private Team createTeam() {
        User user = User.builder()
                .email("sp-test-" + UUID.randomUUID() + "@test.com")
                .passwordHash("hashed")
                .displayName("Test User")
                .build();
        em.persistAndFlush(user);

        Team team = Team.builder()
                .name("SP Team " + UUID.randomUUID())
                .owner(user)
                .build();
        return em.persistAndFlush(team);
    }

    @Test
    void createServiceProfile_allFields_persistsCorrectly() {
        Team team = createTeam();

        ServiceProfile sp = ServiceProfile.builder()
                .serviceName("postgres-service")
                .displayName("PostgreSQL Database")
                .description("Primary relational database")
                .imageName("postgres")
                .imageTag("16")
                .command("postgres -c max_connections=200")
                .workingDir("/var/lib/postgresql")
                .healthCheckCommand("pg_isready -U postgres")
                .healthCheckIntervalSeconds(15)
                .healthCheckTimeoutSeconds(5)
                .healthCheckRetries(5)
                .restartPolicy(RestartPolicy.ALWAYS)
                .memoryLimitMb(512)
                .cpuLimit(2.0)
                .startOrder(1)
                .team(team)
                .build();

        ServiceProfile saved = em.persistAndFlush(sp);
        em.clear();

        ServiceProfile found = em.find(ServiceProfile.class, saved.getId());
        assertThat(found.getId()).isNotNull();
        assertThat(found.getServiceName()).isEqualTo("postgres-service");
        assertThat(found.getDisplayName()).isEqualTo("PostgreSQL Database");
        assertThat(found.getImageName()).isEqualTo("postgres");
        assertThat(found.getImageTag()).isEqualTo("16");
        assertThat(found.getHealthCheckCommand()).isEqualTo("pg_isready -U postgres");
        assertThat(found.getHealthCheckIntervalSeconds()).isEqualTo(15);
        assertThat(found.getRestartPolicy()).isEqualTo(RestartPolicy.ALWAYS);
        assertThat(found.getMemoryLimitMb()).isEqualTo(512);
        assertThat(found.getCpuLimit()).isEqualTo(2.0);
        assertThat(found.getStartOrder()).isEqualTo(1);
    }

    @Test
    void createServiceProfile_defaults_appliedCorrectly() {
        Team team = createTeam();

        ServiceProfile sp = ServiceProfile.builder()
                .serviceName("defaults-test")
                .imageName("nginx")
                .team(team)
                .build();

        ServiceProfile saved = em.persistAndFlush(sp);
        em.clear();

        ServiceProfile found = em.find(ServiceProfile.class, saved.getId());
        assertThat(found.getImageTag()).isEqualTo("latest");
        assertThat(found.getHealthCheckIntervalSeconds()).isEqualTo(30);
        assertThat(found.getHealthCheckTimeoutSeconds()).isEqualTo(10);
        assertThat(found.getHealthCheckRetries()).isEqualTo(3);
        assertThat(found.getRestartPolicy()).isEqualTo(RestartPolicy.UNLESS_STOPPED);
        assertThat(found.getStartOrder()).isZero();
    }

    @Test
    void booleanDefaults_isAutoGenerated_defaultsFalse() {
        Team team = createTeam();

        ServiceProfile sp = ServiceProfile.builder()
                .serviceName("bool-auto-gen")
                .imageName("alpine")
                .team(team)
                .build();

        ServiceProfile saved = em.persistAndFlush(sp);
        em.clear();

        ServiceProfile found = em.find(ServiceProfile.class, saved.getId());
        assertThat(found.isAutoGenerated()).isFalse();
    }

    @Test
    void booleanDefaults_isEnabled_defaultsTrue() {
        Team team = createTeam();

        ServiceProfile sp = ServiceProfile.builder()
                .serviceName("bool-enabled")
                .imageName("alpine")
                .team(team)
                .build();

        ServiceProfile saved = em.persistAndFlush(sp);
        em.clear();

        ServiceProfile found = em.find(ServiceProfile.class, saved.getId());
        assertThat(found.isEnabled()).isTrue();
    }

    @Test
    void collectionInitialization_volumeMounts_emptyByDefault() {
        Team team = createTeam();

        ServiceProfile sp = ServiceProfile.builder()
                .serviceName("collections-vm")
                .imageName("alpine")
                .team(team)
                .build();

        ServiceProfile saved = em.persistAndFlush(sp);
        em.clear();

        ServiceProfile found = em.find(ServiceProfile.class, saved.getId());
        assertThat(found.getVolumeMounts()).isNotNull().isEmpty();
    }

    @Test
    void collectionInitialization_portMappings_emptyByDefault() {
        Team team = createTeam();

        ServiceProfile sp = ServiceProfile.builder()
                .serviceName("collections-pm")
                .imageName("alpine")
                .team(team)
                .build();

        ServiceProfile saved = em.persistAndFlush(sp);
        em.clear();

        ServiceProfile found = em.find(ServiceProfile.class, saved.getId());
        assertThat(found.getPortMappings()).isNotNull().isEmpty();
        assertThat(found.getNetworkConfigs()).isNotNull().isEmpty();
        assertThat(found.getEnvironmentVariables()).isNotNull().isEmpty();
    }

    @Test
    void cascadePersist_volumeMount_persistedWithProfile() {
        Team team = createTeam();

        ServiceProfile sp = ServiceProfile.builder()
                .serviceName("cascade-test")
                .imageName("postgres")
                .team(team)
                .build();

        ServiceProfile saved = em.persistAndFlush(sp);

        VolumeMount vm = VolumeMount.builder()
                .containerPath("/var/lib/postgresql/data")
                .volumeName("pgdata")
                .serviceProfile(saved)
                .build();
        saved.getVolumeMounts().add(vm);

        em.persistAndFlush(saved);
        em.clear();

        ServiceProfile found = em.find(ServiceProfile.class, saved.getId());
        assertThat(found.getVolumeMounts()).hasSize(1);
        assertThat(found.getVolumeMounts().get(0).getContainerPath())
                .isEqualTo("/var/lib/postgresql/data");
        assertThat(found.getVolumeMounts().get(0).getVolumeName())
                .isEqualTo("pgdata");
    }
}
